### ISSUE TITLE
yarn kbn bootstrap failed

### ISSUE THREAD

**Issue by opsnull** [opendistro-for-elasticsearch/alerting-kibana-plugin#11]
kibana v6.6.2

``` bash
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/kibana-extra/opendistro-elasticsearch-alerting-kibana# yarn kbn bootstrap
yarn run v1.15.2
$ node ../../kibana/scripts/kbn bootstrap
Running [bootstrap] command from [/root/kibana]:

Found [28] projects:

kibana
├── packages
│   ├── elastic-datemath (@elastic/datemath)
│   ├── eslint-config-kibana (@elastic/eslint-config-kibana)
│   ├── eslint-plugin-kibana-custom (@elastic/eslint-plugin-kibana-custom)
│   ├── kbn-babel-code-parser (@kbn/babel-code-parser)
│   ├── kbn-babel-preset (@kbn/babel-preset)
│   ├── kbn-config-schema (@kbn/config-schema)
│   ├── kbn-dev-utils (@kbn/dev-utils)
│   ├── kbn-es-query (@kbn/es-query)
│   ├── kbn-es (@kbn/es)
│   ├── kbn-eslint-import-resolver-kibana (@kbn/eslint-import-resolver-kibana)
│   ├── kbn-eslint-plugin-license-header (@kbn/eslint-plugin-license-header)
│   ├── kbn-i18n (@kbn/i18n)
│   ├── kbn-interpreter (@kbn/interpreter)
│   ├── kbn-plugin-generator (@kbn/plugin-generator)
│   ├── kbn-plugin-helpers (@kbn/plugin-helpers)
│   ├── kbn-pm (@kbn/pm)
│   ├── kbn-system-loader (@kbn/system-loader)
│   ├── kbn-test-subj-selector (@kbn/test-subj-selector)
│   ├── kbn-test (@kbn/test)
│   └── kbn-ui-framework (@kbn/ui-framework)
├── test/plugin_functional/plugins
│   ├── kbn_tp_custom_visualizations
│   ├── kbn_tp_sample_app_plugin
│   ├── kbn_tp_sample_panel_action
│   └── kbn_tp_visualize_embedding
├── x-pack (x-pack)
│   └── plugins/infra
└── ../kibana-extra/opendistro-elasticsearch-alerting-kibana (opendistro-alerting)

Running installs in topological order:


Installing dependencies in [kibana]:

$ node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Skipping workspace project: @elastic/datemath
Skipping workspace project: @elastic/eslint-config-kibana
Skipping workspace project: @elastic/eslint-plugin-kibana-custom
Skipping workspace project: @kbn/babel-code-parser
Skipping workspace project: @kbn/babel-preset
Skipping workspace project: @kbn/config-schema
Skipping workspace project: @kbn/dev-utils
Skipping workspace project: @kbn/es-query
Skipping workspace project: @kbn/es
Skipping workspace project: @kbn/eslint-import-resolver-kibana
Skipping workspace project: @kbn/eslint-plugin-license-header
Skipping workspace project: @kbn/i18n
Skipping workspace project: @kbn/interpreter
Skipping workspace project: @kbn/plugin-generator
Skipping workspace project: @kbn/plugin-helpers
Skipping workspace project: @kbn/pm
Skipping workspace project: @kbn/system-loader
Skipping workspace project: @kbn/test-subj-selector
Skipping workspace project: @kbn/test
Skipping workspace project: @kbn/ui-framework
Skipping workspace project: kbn_tp_custom_visualizations
Skipping workspace project: kbn_tp_sample_app_plugin
Skipping workspace project: kbn_tp_sample_panel_action
Skipping workspace project: kbn_tp_visualize_embedding
Skipping workspace project: x-pack
Skipping workspace project: infra


Installing dependencies in [opendistro-alerting]:

[1/4] Resolving packages...
success Already up-to-date.

Installs completed, linking package executables:

[x-pack] plugin-helpers -> ../packages/kbn-plugin-helpers/bin/plugin-helpers.js
[opendistro-alerting] plugin-helpers -> ../../kibana/packages/kbn-plugin-helpers/bin/plugin-helpers.js

Linking executables completed, running `kbn:bootstrap` scripts

@elastic/datemath: $ yarn build --quiet
@kbn/config-schema: $ yarn build
@kbn/config-schema: $ tsc
@elastic/datemath: $ babel src --out-dir target --copy-files --quiet
@kbn/es-query: $ yarn build
@kbn/dev-utils: $ yarn build --quiet
@kbn/babel-code-parser: $ yarn build --quiet
@kbn/babel-code-parser: $ babel src --out-dir target --quiet
@kbn/dev-utils: $ babel src --out-dir target --quiet
@kbn/es-query: $ babel src --out-dir target
@kbn/es-query: src/es_query/__tests__/_migrate_filter.js -> target/es_query/__tests__/_migrate_filter.js
@kbn/es-query: src/es_query/__tests__/build_es_query.js -> target/es_query/__tests__/build_es_query.js
@kbn/es-query: src/es_query/__tests__/decorate_query.js -> target/es_query/__tests__/decorate_query.js
@kbn/es-query: src/es_query/__tests__/from_filters.js -> target/es_query/__tests__/from_filters.js
@kbn/es-query: src/es_query/__tests__/from_kuery.js -> target/es_query/__tests__/from_kuery.js
@kbn/es-query: src/es_query/__tests__/from_lucene.js -> target/es_query/__tests__/from_lucene.js
@kbn/es-query: src/es_query/__tests__/lucene_string_to_dsl.js -> target/es_query/__tests__/lucene_string_to_dsl.js
@kbn/es-query: src/es_query/build_es_query.js -> target/es_query/build_es_query.js
@kbn/es-query: src/es_query/decorate_query.js -> target/es_query/decorate_query.js
@kbn/es-query: src/es_query/from_filters.js -> target/es_query/from_filters.js
@kbn/es-query: src/es_query/from_kuery.js -> target/es_query/from_kuery.js
@kbn/es-query: src/es_query/from_lucene.js -> target/es_query/from_lucene.js
@kbn/es-query: src/es_query/index.js -> target/es_query/index.js
@kbn/es-query: src/es_query/lucene_string_to_dsl.js -> target/es_query/lucene_string_to_dsl.js
@kbn/es-query: src/es_query/migrate_filter.js -> target/es_query/migrate_filter.js
@kbn/es-query: src/filters/__tests__/phrase.js -> target/filters/__tests__/phrase.js
@kbn/es-query: src/filters/__tests__/query.js -> target/filters/__tests__/query.js
@kbn/es-query: src/filters/__tests__/range.js -> target/filters/__tests__/range.js
@kbn/es-query: src/filters/exists.js -> target/filters/exists.js
@kbn/es-query: src/filters/index.js -> target/filters/index.js
@kbn/es-query: src/filters/phrase.js -> target/filters/phrase.js
@kbn/es-query: src/filters/phrases.js -> target/filters/phrases.js
@kbn/es-query: src/filters/query.js -> target/filters/query.js
@kbn/es-query: src/filters/range.js -> target/filters/range.js
@kbn/es-query: src/index.js -> target/index.js
@kbn/es-query: src/kuery/ast/__tests__/ast.js -> target/kuery/ast/__tests__/ast.js
@kbn/es-query: src/kuery/ast/ast.js -> target/kuery/ast/ast.js
@kbn/es-query: src/kuery/ast/index.js -> target/kuery/ast/index.js
@kbn/es-query: src/kuery/ast/kuery.js -> target/kuery/ast/kuery.js
@kbn/es-query: src/kuery/ast/legacy_kuery.js -> target/kuery/ast/legacy_kuery.js
@kbn/es-query: src/kuery/filter_migration/__tests__/exists.js -> target/kuery/filter_migration/__tests__/exists.js
@kbn/es-query: src/kuery/filter_migration/__tests__/filter_to_kuery.js -> target/kuery/filter_migration/__tests__/filter_to_kuery.js
@kbn/es-query: src/kuery/filter_migration/__tests__/geo_bounding_box.js -> target/kuery/filter_migration/__tests__/geo_bounding_box.js
@kbn/es-query: src/kuery/filter_migration/__tests__/geo_polygon.js -> target/kuery/filter_migration/__tests__/geo_polygon.js
@kbn/es-query: src/kuery/filter_migration/__tests__/phrase.js -> target/kuery/filter_migration/__tests__/phrase.js
@kbn/es-query: src/kuery/filter_migration/__tests__/range.js -> target/kuery/filter_migration/__tests__/range.js
@kbn/es-query: src/kuery/filter_migration/exists.js -> target/kuery/filter_migration/exists.js
@kbn/es-query: src/kuery/filter_migration/filter_to_kuery.js -> target/kuery/filter_migration/filter_to_kuery.js
@kbn/es-query: src/kuery/filter_migration/geo_bounding_box.js -> target/kuery/filter_migration/geo_bounding_box.js
@kbn/es-query: src/kuery/filter_migration/geo_polygon.js -> target/kuery/filter_migration/geo_polygon.js
@kbn/es-query: src/kuery/filter_migration/index.js -> target/kuery/filter_migration/index.js
@kbn/es-query: src/kuery/filter_migration/phrase.js -> target/kuery/filter_migration/phrase.js
@kbn/es-query: src/kuery/filter_migration/range.js -> target/kuery/filter_migration/range.js
@kbn/es-query: src/kuery/functions/__tests__/and.js -> target/kuery/functions/__tests__/and.js
@kbn/es-query: src/kuery/functions/__tests__/exists.js -> target/kuery/functions/__tests__/exists.js
@kbn/es-query: src/kuery/functions/__tests__/geo_bounding_box.js -> target/kuery/functions/__tests__/geo_bounding_box.js
@kbn/es-query: src/kuery/functions/__tests__/geo_polygon.js -> target/kuery/functions/__tests__/geo_polygon.js
@kbn/es-query: src/kuery/functions/__tests__/is.js -> target/kuery/functions/__tests__/is.js
@kbn/es-query: src/kuery/functions/__tests__/not.js -> target/kuery/functions/__tests__/not.js
@kbn/es-query: src/kuery/functions/__tests__/or.js -> target/kuery/functions/__tests__/or.js
@kbn/es-query: src/kuery/functions/__tests__/range.js -> target/kuery/functions/__tests__/range.js
@kbn/es-query: src/kuery/functions/__tests__/utils/get_fields.js -> target/kuery/functions/__tests__/utils/get_fields.js
@kbn/es-query: src/kuery/functions/and.js -> target/kuery/functions/and.js
@kbn/es-query: src/kuery/functions/exists.js -> target/kuery/functions/exists.js
@kbn/es-query: src/kuery/functions/geo_bounding_box.js -> target/kuery/functions/geo_bounding_box.js
@kbn/es-query: src/kuery/functions/geo_polygon.js -> target/kuery/functions/geo_polygon.js
@kbn/es-query: src/kuery/functions/index.js -> target/kuery/functions/index.js
@kbn/es-query: src/kuery/functions/is.js -> target/kuery/functions/is.js
@kbn/es-query: src/kuery/functions/not.js -> target/kuery/functions/not.js
@kbn/es-query: src/kuery/functions/or.js -> target/kuery/functions/or.js
@kbn/es-query: src/kuery/functions/range.js -> target/kuery/functions/range.js
@kbn/es-query: src/kuery/functions/utils/get_fields.js -> target/kuery/functions/utils/get_fields.js
@kbn/es-query: src/kuery/index.js -> target/kuery/index.js
@kbn/es-query: src/kuery/node_types/__tests__/function.js -> target/kuery/node_types/__tests__/function.js
@kbn/es-query: src/kuery/node_types/__tests__/literal.js -> target/kuery/node_types/__tests__/literal.js
@kbn/es-query: src/kuery/node_types/__tests__/named_arg.js -> target/kuery/node_types/__tests__/named_arg.js
@kbn/es-query: src/kuery/node_types/__tests__/wildcard.js -> target/kuery/node_types/__tests__/wildcard.js
@kbn/es-query: src/kuery/node_types/function.js -> target/kuery/node_types/function.js
@kbn/es-query: src/kuery/node_types/index.js -> target/kuery/node_types/index.js
@kbn/es-query: src/kuery/node_types/literal.js -> target/kuery/node_types/literal.js
@kbn/es-query: src/kuery/node_types/named_arg.js -> target/kuery/node_types/named_arg.js
@kbn/es-query: src/kuery/node_types/wildcard.js -> target/kuery/node_types/wildcard.js
@kbn/interpreter: $ node scripts/build --dev
@kbn/i18n: $ node scripts/build --source-maps
@kbn/test: $ yarn build --quiet
@kbn/interpreter:  info Deleting old output
@kbn/i18n:  info Deleting old output
@kbn/interpreter:  info Starting babel and webpack
@kbn/interpreter:  info [babel  ] > babel src --ignore src/plugin,*.test.js --out-dir target --copy-files --source-maps inline --quiet
@kbn/i18n:  info Starting babel and typescript
@kbn/i18n:  info [babel:web ] > babel src --config-file /root/kibana/packages/kbn-i18n/babel.config.js --out-dir /root/kibana/packages/kbn-i18n/target/web --extensions .ts,.js,.tsx --quiet --source-map inline
@kbn/interpreter:  info [webpack] > webpack --config tasks/build/webpack.config.js --env.sourceMaps true
@kbn/i18n:  info [babel:node] > babel src --config-file /root/kibana/packages/kbn-i18n/babel.config.js --out-dir /root/kibana/packages/kbn-i18n/target/node --extensions .ts,.js,.tsx --quiet --source-map inline
@kbn/i18n:  info [tsc       ] > tsc --emitDeclarationOnly --declarationMap true
@kbn/test: $ babel src --out-dir target --quiet
@kbn/i18n:  proc [babel:web ] Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
@kbn/i18n:  proc [babel:node] Successfully compiled 18 files with Babel.
@kbn/i18n:  info [babel:node] exited with 0 after a few seconds
@kbn/interpreter:  info [babel  ] exited with 0 after a few seconds
@kbn/i18n:  proc [babel:web ] Successfully compiled 18 files with Babel.
@kbn/i18n:  info [babel:web ] exited with 0 after a few seconds
@kbn/interpreter:  info [webpack] exited with 0 after a few seconds
@kbn/interpreter:  succ Complete
@kbn/i18n:  info [tsc       ] exited with 0 after a few seconds
@kbn/i18n:  succ Complete
x-pack: $ gulp canvas:plugins:build
x-pack: [14:44:48] /root/kibana/x-pack/plugins/canvas/canvas_plugin
x-pack: [14:44:48] Using gulpfile ~/kibana/x-pack/gulpfile.js
x-pack: [14:44:48] Starting 'canvas:plugins:build'...
✖ x-pack: Killed
x-pack: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ x-pack: error Command failed with exit code 137.

[bootstrap] failed:

Error: Command failed: yarn run kbn:bootstrap
Killed
error Command failed with exit code 137.

$ gulp canvas:plugins:build
[14:44:48] /root/kibana/x-pack/plugins/canvas/canvas_plugin
[14:44:48] Using gulpfile ~/kibana/x-pack/gulpfile.js
[14:44:48] Starting 'canvas:plugins:build'...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at makeError (/root/kibana/packages/kbn-pm/dist/index.js:14111:9)
    at Promise.all.then.arr (/root/kibana/packages/kbn-pm/dist/index.js:14215:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mihirsoni** [comment]
Hi @opsnull 

Thanks for filing an issue. 
I did try building again from scratch it seems okay to me.

Could you ensure that you're using right kibana branch and not `master` branch, you could try using git tags `git checkout tags/v6.6.2`.

**Comment by mihirsoni** [comment]
Hi @opsnull 
Closing this issue. Feel free to re-open in case still an issue.
