### ISSUE TITLE
Error during launch of v1.10 in Kibana 7.9.0. Can't resolve 'ui/autoload/styles'.

### ISSUE THREAD

**Issue by failytaler** [opendistro-for-elasticsearch/alerting-kibana-plugin#178]
Here is log from Kibana 7.9.0. It starts ok without the plugin, but with plugin the next is happening
```
{"type":"log","@timestamp":"2020-08-26T18:18:20Z","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: beats_management"}
{"type":"log","@timestamp":"2020-08-26T18:18:20Z","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: triggers_actions_ui"}
[BABEL] Note: The code generator has deoptimised the styling of /usr/share/kibana/x-pack/plugins/canvas/server/templates/pitch_presentation.js as it exceeds the max of 500KB.
{"type":"log","@timestamp":"2020-08-26T18:19:19Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2020-08-26T18:19:19Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"auditTrail\" is disabled."}
{"type":"log","@timestamp":"2020-08-26T18:19:21Z","tags":["warning","legacy-service"],"pid":6,"message":"Some installed third party plugin(s) [opendistro-alerting] are using the legacy plugin format and will no longer work in a future Kibana release. Please refer to https://ela.st/kibana-breaking-changes-8-0 for a list of breaking changes and https://ela.st/kibana-platform-migration for documentation on how to migrate legacy plugins."}
{"type":"log","@timestamp":"2020-08-26T18:19:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"\"xpack.monitoring.ui.container.elasticsearch.enabled\" is deprecated and has been replaced by \"monitoring.ui.container.elasticsearch.enabled\""}
{"type":"log","@timestamp":"2020-08-26T18:19:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"\"xpack.monitoring\" is deprecated and has been replaced by \"monitoring\". However both key are present, ignoring \"xpack.monitoring\""}
{"type":"log","@timestamp":"2020-08-26T18:19:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"Config key [monitoring.cluster_alerts.email_notifications.email_address] will be required for email notifications to work in 8.0.\""}
{"type":"log","@timestamp":"2020-08-26T18:19:21Z","tags":["info","plugins-system"],"pid":6,"message":"Setting up [92] plugins: [taskManager,licensing,observability,globalSearch,globalSearchProviders,code,usageCollection,ossTelemetry,telemetryCollectionManager,telemetry,telemetryCollectionXpack,kibanaUsageCollection,newsfeed,mapsLegacy,kibanaLegacy,translations,timelion,share,legacyExport,esUiShared,charts,bfetch,expressions,data,home,cloud,console,consoleExtensions,apmOss,searchprofiler,painlessLab,grokdebugger,management,upgradeAssistant,licenseManagement,watcher,indexPatternManagement,advancedSettings,fileUpload,dataEnhanced,savedObjects,visualizations,visualize,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,features,security,snapshotRestore,reporting,enterpriseSearch,encryptedSavedObjects,ingestManager,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,beats_management,transform,ingestPipelines,maps,graph,canvas,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeMarkdown,tileMap,regionMap,inputControlVis,discover,discoverEnhanced,dashboard,lens,dashboardMode,savedObjectsManagement,spaces,lists,eventLog,actions,case,alerts,alertingBuiltins,ml,securitySolution,infra,monitoring,logstash,apm,uptime]"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","reporting","config"],"pid":6,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","reporting","config"],"pid":6,"message":"Found 'server.host: \"0\"' in Kibana configuration. This is incompatible with Reporting. To enable Reporting to work, 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can change the setting to 'server.host: 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this message."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","encryptedSavedObjects","config"],"pid":6,"message":"Generating a random key for xpack.encryptedSavedObjects.encryptionKey. To be able to decrypt encrypted saved objects attributes after restart, please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","ingestManager"],"pid":6,"message":"Fleet APIs are disabled due to the Encrypted Saved Objects plugin using an ephemeral encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","actions","actions"],"pid":6,"message":"APIs are disabled due to the Encrypted Saved Objects plugin using an ephemeral encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","alerts","plugins","alerting"],"pid":6,"message":"APIs are disabled due to the Encrypted Saved Objects plugin using an ephemeral encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","plugins","monitoring","monitoring"],"pid":6,"message":"config sourced from: production cluster"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","monitoring","monitoring"],"pid":6,"message":"X-Pack Monitoring Cluster Alerts will not be available: undefined"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["warning","plugins","reporting","config"],"pid":6,"message":"Chromium sandbox provides an additional layer of protection, but is not supported for Linux Centos 7.8.2003 OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","savedobjects-service"],"pid":6,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","savedobjects-service"],"pid":6,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","plugins-system"],"pid":6,"message":"Starting [92] plugins: [taskManager,licensing,observability,globalSearch,globalSearchProviders,code,usageCollection,ossTelemetry,telemetryCollectionManager,telemetry,telemetryCollectionXpack,kibanaUsageCollection,newsfeed,mapsLegacy,kibanaLegacy,translations,timelion,share,legacyExport,esUiShared,charts,bfetch,expressions,data,home,cloud,console,consoleExtensions,apmOss,searchprofiler,painlessLab,grokdebugger,management,upgradeAssistant,licenseManagement,watcher,indexPatternManagement,advancedSettings,fileUpload,dataEnhanced,savedObjects,visualizations,visualize,visTypeVislib,visTypeVega,visTypeTimeseries,visTypeTimelion,features,security,snapshotRestore,reporting,enterpriseSearch,encryptedSavedObjects,ingestManager,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,beats_management,transform,ingestPipelines,maps,graph,canvas,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeMarkdown,tileMap,regionMap,inputControlVis,discover,discoverEnhanced,dashboard,lens,dashboardMode,savedObjectsManagement,spaces,lists,eventLog,actions,case,alerts,alertingBuiltins,ml,securitySolution,infra,monitoring,logstash,apm,uptime]"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","plugins","taskManager","taskManager"],"pid":6,"message":"TaskManager is identified by the Kibana UUID: 3a4dc9fa-5f95-4d85-86a5-52d3693927f3"}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","plugins","watcher"],"pid":6,"message":"Your basic license does not support watcher. Please upgrade your license."}
{"type":"log","@timestamp":"2020-08-26T18:19:22Z","tags":["info","plugins","crossClusterReplication"],"pid":6,"message":"Your basic license does not support crossClusterReplication. Please upgrade your license."}
{"type":"log","@timestamp":"2020-08-26T18:19:23Z","tags":["info","plugins","monitoring","monitoring","kibana-monitoring"],"pid":6,"message":"Starting monitoring stats collection"}
{"type":"log","@timestamp":"2020-08-26T18:19:25Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for opendistro-alerting, status_page and timelion. This may take a few minutes"}
Error in worker TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
Error in worker TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
Error in worker TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
{"type":"log","@timestamp":"2020-08-26T18:19:32Z","tags":["warning","plugins","reporting"],"pid":6,"message":"Enabling the Chromium sandbox provides an additional layer of protection."}
{"type":"log","@timestamp":"2020-08-26T18:20:22Z","tags":["fatal","root"],"pid":6,"message":"{ Error: Optimizations failure.\n   706 modules\n    \n    ERROR in ./plugins/opendistro-alerting/public/app.js\n    Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/opendistro-alerting/public'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:433:26)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n  cause:\n   { Error: Optimizations failure.\n      706 modules\n       \n       ERROR in ./plugins/opendistro-alerting/public/app.js\n       Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/opendistro-alerting/public'\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:433:26)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:681:15)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:678:31)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1423:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.41.5',\n        hash: 'ebfe5942ce399f8a1c88',\n        time: 56408,\n        builtAt: 1598466022105,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        logging: [Object],\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ './plugins/opendistro-alerting/public/app.js\\nModule not found: Error: Can\\'t resolve \\'ui/autoload/styles\\' in \\'/usr/share/kibana/plugins/opendistro-alerting/public\\'\\nresolve \\'ui/autoload/styles\\' in \\'/usr/share/kibana/plugins/opendistro-alerting/public\\'\\n  Parsed request is a module\\n  using description file: /usr/share/kibana/plugins/opendistro-alerting/package.json (relative path: ./public)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/legacy/ui/public\\' to \\'/usr/share/kibana/src/legacy/ui/public/autoload/styles\\'\\n      using description file: /usr/share/kibana/plugins/opendistro-alerting/package.json (relative path: ./public)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/legacy/ui/public/autoload/styles)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.js doesn\\'t exist\\n          .ts\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.ts doesn\\'t exist\\n          .tsx\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.tsx doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/legacy/ui/public/autoload/styles doesn\\'t exist\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.js]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.ts]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.tsx]\\n[/usr/share/kibana/src/legacy/ui/public/autoload/styles.json]\\n @ ./plugins/opendistro-alerting/public/app.js 23:0-28\\n @ ./optimize/bundles/opendistro-alerting.entry.js' ],\n     warnings: [],\n     version: '4.41.5',\n     hash: 'ebfe5942ce399f8a1c88',\n     time: 56408,\n     builtAt: 1598466022105,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n      { dark_theme: [Array],\n        light_theme: [Array],\n        'opendistro-alerting': [Array],\n        status_page: 'status_page.bundle.js',\n        timelion: 'timelion.bundle.js' },\n     assets:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints:\n      { 'opendistro-alerting': [Object],\n        status_page: [Object],\n        timelion: [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     namedChunkGroups:\n      { 'opendistro-alerting': [Object],\n        status_page: [Object],\n        timelion: [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     chunks:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     modules:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 606 more items ],\n     filteredModules: 0,\n     logging: { 'webpack.buildChunkGraph.visitModules': [Object] },\n     children:\n      [ [Object], [Object], [Object], [Object], [Object], [Object] ] },\n  isBoom: true,\n  isServer: true,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
{"type":"log","@timestamp":"2020-08-26T18:20:22Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}

 FATAL  Error: Optimizations failure.
   706 modules
    
    ERROR in ./plugins/opendistro-alerting/public/app.js
    Module not found: Error: Can't resolve 'ui/autoload/styles' in '/usr/share/kibana/plugins/opendistro-alerting/public'
```

**Comment by bowenlan-amzn** [comment]
Thanks for reporting this

**Comment by failytaler** [comment]
@bowenlan-amzn When are you going to make new 1.10 release available for download?

**Comment by bowenlan-amzn** [comment]
the fix is merged, please try build again @failytaler
