### ISSUE TITLE
Root mapping definition has unsupported parameters when creating monitor

### ISSUE THREAD

**Issue by dennyx** [opendistro-for-elasticsearch/alerting-kibana-plugin#87]
Hi,
Opendistro version: **1.1.0**
Issue:
When trying to create monitor in kibana alert panel, while could not found any data in UI, and check elasticsearch logs, get below errors.
Expected could successfully get data in create monitor page.
Appreciate if any kindly help, thanks.
`[2019-09-06T09:00:39,700][ERROR][c.a.o.a.MonitorRunner    ] [elasticcluster] Error loading alerts for monitor: _na_
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:394) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:476) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) ~[?:?]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_doc : {}]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:152) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:392) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 15 more`
![image](https://user-images.githubusercontent.com/8176446/64416973-c5ae0c80-d0ca-11e9-9c41-78f8dd43a4f7.png)

**Comment by dbbaughe** [comment]
Hi @dennyx,

For some more context, was this a new 7.1 cluster or a cluster you upgraded from an earlier version? This seems to be a bug on our backend plugin. Potentially related to our updating of alert index mappings.

**Comment by dennyx** [comment]
@dbbaughe 
Thanks for the kindly feedback.
This is a new 7.1 cluster.
Appreciate if any workground could help on this, thanks~

**Comment by mmiller1** [comment]
I'm getting the same error when trying to preview alerts in kibana, after I save them, the error looks slightly different when they try to run on the data node vs the client node that kibana connects to.
```
elasticsearch-data-1 elasticsearch [2019-12-04T21:55:04,713][ERROR][c.a.o.a.MonitorRunner    ] [elasticsearch-data-1] Error loading alerts for monitor: Ktnf0m4BkWqsTIwjrmCI
elasticsearch-data-1 elasticsearch org.elasticsearch.transport.RemoteTransportException: [elasticsearch-master-2][10.244.168.12:9300][indices:admin/create]
elasticsearch-data-1 elasticsearch Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_doc : {}]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:327) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:476) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.2.0.jar:7.2.0]
elasticsearch-data-1 elasticsearch 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
elasticsearch-data-1 elasticsearch 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
elasticsearch-data-1 elasticsearch 	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```
This is on a new 7.2 cluster.

**Comment by dbbaughe** [comment]
Closing this in favor of https://github.com/opendistro-for-elasticsearch/alerting/issues/103 as it is an issue with the mappings being populated in the index.
